### ISSUE TITLE
”关于我“里面的公众号二维码崩了，可能是图片太大了

### ISSUE THREAD

**Issue by maddama** [guanpengchn/guanpengchn.github.io#78]
![image](https://user-images.githubusercontent.com/42434686/61930851-e879cc80-af33-11e9-9835-4235a588b7e9.png)

**Comment by guanpengchn** [comment]
![二维码](https://user-images.githubusercontent.com/13995641/61989561-0fcfb700-b064-11e9-994e-9357bd192ca6.gif)

哈哈，补一个，这个博客我也是很久不维护了
